- name: dnf install mysql-server -y
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: systemctl enable mysqld
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9 # pip3.11 if python version is 3.11  

- name: import role common
  ansible.builtin.import.role:
    name: common
    vars_from: vars/main.yaml        

- name: check password set or not
  community.mysql.mysql_info:    
    login_user: "{{login_user}}"
    login_password: "{{login_password}}"
    login_host: "{{login_host}}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: password set
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ login_password }}"
  when: mysql_connection_output.failed is true